Try avoiding a rare crash we cnanot reproduce. Crash is:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nll.helper/com.nll.helper.ui.MainActivity}: android.app.Fragment$InstantiationException: Unable to instantiate fragment androidx.lifecycle.E: could not find Fragment constructor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4184)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4340)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment androidx.lifecycle.E: could not find Fragment constructor
at android.app.Fragment.instantiate(Fragment.java:562)
at android.app.FragmentContainer.instantiate(FragmentContainer.java:53)
at android.app.FragmentState.instantiate(FragmentState.java:77)
at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:2867)
at android.app.FragmentController.restoreAllState(FragmentController.java:143)
at android.app.Activity.onCreate(Activity.java:1698)
at C.g.onCreate(ComponentActivity.java:1)
at a.i.onCreate(ComponentActivity.java:35)
at a0.o.onCreate(FragmentActivity.java:1)
at com.nll.helper.ui.MainActivity.onCreate(MainActivity.kt:3)
at android.app.Activity.performCreate(Activity.java:8657)
at android.app.Activity.performCreate(Activity.java:8636)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4165)
... 12 more
Caused by: java.lang.NoSuchMethodException: androidx.lifecycle.E.<init> []
at java.lang.Class.getConstructor0(Class.java:3325)
at java.lang.Class.getConstructor(Class.java:2485)
at android.app.Fragment.instantiate(Fragment.java:543)
... 25 more